Prefix: '§7§l[§f§lBlack§8§lMC§7§l] §5§l»'
Limits:
  golden_apple:
    limit: 16
    slot: 10
    page: 1
    name: "Złote jabłko"
  enchanted_golden_apple:
    limit: 2
    slot: 11
    page: 1
    name: "Zaklęte złote jabłko"
  totem_of_undying:
    limit: 2
    slot: 12
    page: 1
    name: "Totem nieśmiertelności"
  ender_pearl:
    limit: 2
    slot: 13
    page: 1
    name: "Ender perła"
  end_crystal:
    limit: 2
    slot: 14
    page: 1
    name: "Kryształ kresu"